# Generated by Django 5.2.7 on 2025-11-28 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_instrument_song_instruments'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='visit_id',
            field=models.CharField(default='TEMP', max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
