# Generated by Django 5.2.7 on 2025-12-12 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_visit_visit_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='audio',
        ),
        migrations.AddField(
            model_name='song',
            name='audio_path',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
