# Generated by Django 5.2.7 on 2025-12-29 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_song_audio_song_audio_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visit',
            name='visit_id',
        ),
        migrations.AddField(
            model_name='song',
            name='catalogue_id',
            field=models.CharField(default='none', max_length=12, unique=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='catalogue_id',
            field=models.CharField(default='none', max_length=12, unique=True),
            preserve_default=False,
        ),
    ]
