# Generated by Django 5.2.7 on 2025-12-29 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_visit_visit_id_song_catalogue_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='origin',
            field=models.CharField(max_length=50, null=True, verbose_name='Village/Place of Origin'),
        ),
        migrations.AlterField(
            model_name='song',
            name='catalogue_id',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
