# Generated by Django 5.2.7 on 2025-12-29 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_group_origin_alter_song_catalogue_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='youtube',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
