# Generated by Django 5.2.7 on 2025-12-30 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_song_youtube'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldtrip',
            name='country',
            field=models.CharField(default='country', max_length=50),
            preserve_default=False,
        ),
    ]
