# Generated by Django 5.2.7 on 2026-01-22 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_fieldtrip_country'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='catalogue_id',
            new_name='archive_id',
        ),
        migrations.RenameField(
            model_name='visit',
            old_name='catalogue_id',
            new_name='archive_id',
        ),
        migrations.AddField(
            model_name='fieldtrip',
            name='archive_id',
            field=models.CharField(default='xxxx', max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fieldtrip',
            name='region',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
