# Generated by Django 5.2.7 on 2025-12-30 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_fieldtrip_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldtrip',
            name='trip_id',
            field=models.CharField(default='default', max_length=3, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fieldtrip',
            name='name',
            field=models.CharField(blank=True, default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fieldtrip',
            name='region',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
