# Generated by Django 5.2.7 on 2025-12-30 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_fieldtrip_trip_id_alter_fieldtrip_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldtrip',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='fieldtrip',
            name='region',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
