# Generated by Django 5.2.7 on 2025-12-30 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_fieldtrip_name_alter_fieldtrip_region'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fieldtrip',
            old_name='trip_id',
            new_name='archive_id',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='catalogue_id',
            new_name='archive_id',
        ),
        migrations.RenameField(
            model_name='visit',
            old_name='catalogue_id',
            new_name='archive_id',
        ),
    ]
