# Generated by Django 5.2.7 on 2026-01-22 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_rename_trip_id_fieldtrip_archive_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldtrip',
            name='archive_id',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
